version: '3.0'

services:

  hello-app:
    build: .
    image: hello-app:latest
    container_name: hello-app
    hostname: hello-app
    ports:
      - "8888:8888"
    networks:
      - otel-with-java
    depends_on:
      - collector
      - tempo
    environment:
      - OTEL_TRACES_EXPORTER=jaeger
        #- OTEL_METRICS_EXPORTER=jaeger
        #- OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:55680
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://tempo:14250
        #- OTEL_TRACES_SAMPLER=always_on
        #- OTEL_IMR_EXPORT_INTERVAL=5000
        #- OTEL_RESOURCE_ATTRIBUTES=service.name=hello-app,service.version=1.0
    healthcheck:
      interval: 5s
      retries: 10
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8888/hello

  collector:
    image: otel/opentelemetry-collector:latest
    container_name: collector
    hostname: collector
    command: ["--config=/etc/collector-config.yaml"]
    volumes:
      - ./otel-collector-grafana.yaml:/etc/collector-config.yaml
    ports:
      - "13133:13133"
      - "55680:55680"
      - "14268:14268"
      - "14250:14250"
    networks:
      - otel-with-java
      #    depends_on:
      #apm-server:
      #  condition: service_healthy


  # To eventually offload to Tempo...
  tempo:
    image: grafana/tempo:latest
    hostname: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "14250"  # jaeger grpc
      - "3200"   # tempo
      - "55680"  # otlp grpc
      - "55681"  # otlp http
      - "9411"   # zipkin
    networks:
      - otel-with-java


  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yaml" ]
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
     - otel-with-java

  grafana:
    image: grafana/grafana:8.1.6
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"  
    networks:
      - otel-with-java


networks:
  otel-with-java:
    driver: bridge
